import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import QuesitonsView from '@/components/QuestionView/QuesitonsView'
import HomePage from '@/components/HomePage/HomePage'

const inter = Inter({ subsets: ['latin'] })

export default function questions() {
  return (
    <>
      <Head>
        <title>Micro Model Exam </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QuesitonsView/>
    </>
  )
}
